-- Manual Ajax member roster for M0 (no Wellyx gate).
insert into public.member_roster (tenant_id, email, full_name, status)
values
  ('11111111-1111-1111-1111-111111111111', 'david@ajaxgym.com', 'David Mills', 'active'),
  ('11111111-1111-1111-1111-111111111111', 'seth@ajaxgym.com', 'Seth', 'active'),
  ('11111111-1111-1111-1111-111111111111', 'member@ajax.local', 'Demo Member', 'active'),
  ('11111111-1111-1111-1111-111111111111', 'playwright@ajax.local', 'Playwright Guest', 'active')
on conflict (tenant_id, email) do update
  set full_name = excluded.full_name,
      status = excluded.status;

-- M1 demo block assigned to member@ajax.local (matches InMemoryAjaxStore seed).
insert into public.programs (id, tenant_id, title, notes, duration_weeks)
values (
  '22222222-2222-2222-2222-222222222222',
  '11111111-1111-1111-1111-111111111111',
  'Ajax Foundation — 6 weeks',
  'A first custom block: three sessions a week, strength plus easy aerobic work. Load only when the movement stays quiet and controlled. Every exercise has an in-app form video.',
  6
)
on conflict (id) do update
  set title = excluded.title,
      notes = excluded.notes,
      duration_weeks = excluded.duration_weeks;

insert into public.workouts (tenant_id, program_id, week, day, sort_order, title, notes, video_url, segments)
values
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 1, 1, 0, 'Lower body — settle the pattern',
   'Find depth and a still torso before you chase load. Leave two reps in reserve.',
   'https://www.youtube.com/watch?v=MeIiIdhvXT4',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Nasal if you can. This is just to get warm.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"World''s greatest stretch","prescription":"2 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Glute bridge","prescription":"2 × 8","notes":"Pause at the top. Ribs down.","videoUrl":"https://www.youtube.com/watch?v=WCGV5XWewFY"},{"name":"Ankle rocks","prescription":"2 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Goblet squat","prescription":"3 × 8","notes":"Pause one breath at the bottom.","videoUrl":"https://www.youtube.com/watch?v=MeIiIdhvXT4"},{"name":"Romanian deadlift","prescription":"3 × 6","notes":"Soft knees, long spine.","videoUrl":"https://www.youtube.com/watch?v=jEy_czb3RKA"},{"name":"Calf raise","prescription":"2 × 12","videoUrl":"https://www.youtube.com/watch?v=gwLzBJYoWlI"},{"name":"Dead bug","prescription":"2 × 6 / side","notes":"Low back stays quiet on the floor.","videoUrl":"https://www.youtube.com/watch?v=UBa7wBucN-4"},{"name":"Suitcase carry","prescription":"2 × 20m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 1, 3, 1, 'Upper body — press and pull',
   'Even tempo. Stop the set when the shoulder shrug starts to take over.',
   'https://www.youtube.com/watch?v=0G2_XV7slIg',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Unhurried. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Band pull-apart","prescription":"2 × 12","notes":"Long spine. Stop if the shrug takes over.","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Cat-cow","prescription":"6 breaths","videoUrl":"https://www.youtube.com/watch?v=y39PrKY_4JM"},{"name":"Dumbbell bench press","prescription":"3 × 8","videoUrl":"https://www.youtube.com/watch?v=0G2_XV7slIg"},{"name":"Chest-supported row","prescription":"3 × 8","videoUrl":"https://www.youtube.com/watch?v=pYcpY20QaE8"},{"name":"Half-kneeling press","prescription":"2 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=M2rwvNhTOu0"},{"name":"Face pull","prescription":"2 × 12","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Side plank","prescription":"2 × 20s / side","notes":"Hips stacked. Stop if the low back takes over.","videoUrl":"https://www.youtube.com/watch?v=K2VljzCC16g"},{"name":"Suitcase carry","prescription":"2 × 20m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 1, 5, 2, 'Easy aerobic + mobility',
   'Conversational pace. This is recovery you can still feel proud of.',
   'https://www.youtube.com/watch?v=L_xrDAtykMI',
   '[{"name":"Easy walk-in","prescription":"5 min","notes":"Arrive unhurried.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Zone 2","prescription":"30–40 min walk, bike, or ski-erg","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Hip 90/90","prescription":"2 × 45s / side","videoUrl":"https://www.youtube.com/watch?v=MH919hRvrVE"},{"name":"Couch stretch","prescription":"2 × 40s / side","videoUrl":"https://www.youtube.com/watch?v=ulgAOykAgV4"},{"name":"Breathing reset","prescription":"5 min nasal, slow","videoUrl":"https://www.youtube.com/watch?v=tybOi4hjZFQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 2, 1, 3, 'Lower body — add a little load',
   'Same patterns as week 1. A small jump in weight is enough.',
   'https://www.youtube.com/watch?v=MeIiIdhvXT4',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Nasal if you can. This is just to get warm.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"World''s greatest stretch","prescription":"2 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Glute bridge","prescription":"2 × 8","notes":"Pause at the top. Ribs down.","videoUrl":"https://www.youtube.com/watch?v=WCGV5XWewFY"},{"name":"Ankle rocks","prescription":"2 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Goblet squat","prescription":"3 × 8","videoUrl":"https://www.youtube.com/watch?v=MeIiIdhvXT4"},{"name":"Romanian deadlift","prescription":"3 × 6","notes":"Soft knees, long spine.","videoUrl":"https://www.youtube.com/watch?v=jEy_czb3RKA"},{"name":"Split squat","prescription":"2 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=2C-uNgKwPLE"},{"name":"Dead bug","prescription":"2 × 6 / side","notes":"Low back stays quiet on the floor.","videoUrl":"https://www.youtube.com/watch?v=UBa7wBucN-4"},{"name":"Suitcase carry","prescription":"2 × 20m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 2, 3, 4, 'Upper body — clean positions',
   'Keep the ribs stacked. Do not chase a pump.',
   'https://www.youtube.com/watch?v=0G2_XV7slIg',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Unhurried. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Band pull-apart","prescription":"2 × 12","notes":"Long spine. Stop if the shrug takes over.","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Cat-cow","prescription":"6 breaths","videoUrl":"https://www.youtube.com/watch?v=y39PrKY_4JM"},{"name":"Dumbbell bench press","prescription":"3 × 8","videoUrl":"https://www.youtube.com/watch?v=0G2_XV7slIg"},{"name":"Chest-supported row","prescription":"3 × 10","videoUrl":"https://www.youtube.com/watch?v=pYcpY20QaE8"},{"name":"Face pull","prescription":"2 × 12","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Pallof press","prescription":"2 × 8 / side","notes":"Anti-rotation. Ribs stacked.","videoUrl":"https://www.youtube.com/watch?v=K2VljzCC16g"},{"name":"Side plank","prescription":"2 × 20s / side","notes":"Hips stacked. Stop if the low back takes over.","videoUrl":"https://www.youtube.com/watch?v=K2VljzCC16g"},{"name":"Suitcase carry","prescription":"2 × 20m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 2, 5, 5, 'Easy aerobic + walk-out',
   'Same zone 2 as week 1. Finish with unhurried breathing.',
   'https://www.youtube.com/watch?v=L_xrDAtykMI',
   '[{"name":"Easy walk-in","prescription":"5 min","notes":"Arrive unhurried.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Zone 2","prescription":"35–45 min","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Couch stretch","prescription":"2 × 40s / side","videoUrl":"https://www.youtube.com/watch?v=ulgAOykAgV4"},{"name":"Hip 90/90","prescription":"2 × 45s / side","videoUrl":"https://www.youtube.com/watch?v=MH919hRvrVE"},{"name":"Breathing reset","prescription":"5 min nasal, slow","videoUrl":"https://www.youtube.com/watch?v=tybOi4hjZFQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 3, 1, 6, 'Lower body — density',
   'Shorter rests if the last set still looks like the first.',
   'https://www.youtube.com/watch?v=MeIiIdhvXT4',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Nasal if you can. This is just to get warm.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"World''s greatest stretch","prescription":"2 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Glute bridge","prescription":"2 × 8","notes":"Pause at the top. Ribs down.","videoUrl":"https://www.youtube.com/watch?v=WCGV5XWewFY"},{"name":"Ankle rocks","prescription":"2 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Front-loaded squat","prescription":"4 × 6","videoUrl":"https://www.youtube.com/watch?v=MeIiIdhvXT4"},{"name":"Hip hinge","prescription":"3 × 6","notes":"Soft knees, long spine.","videoUrl":"https://www.youtube.com/watch?v=jEy_czb3RKA"},{"name":"Calf raise","prescription":"3 × 10","videoUrl":"https://www.youtube.com/watch?v=gwLzBJYoWlI"},{"name":"Dead bug","prescription":"2 × 6 / side","notes":"Low back stays quiet on the floor.","videoUrl":"https://www.youtube.com/watch?v=UBa7wBucN-4"},{"name":"Suitcase carry","prescription":"2 × 20m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 3, 3, 7, 'Upper body — denser sets',
   'One extra working set. Form still wins.',
   'https://www.youtube.com/watch?v=0G2_XV7slIg',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Unhurried. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Band pull-apart","prescription":"2 × 12","notes":"Long spine. Stop if the shrug takes over.","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Cat-cow","prescription":"6 breaths","videoUrl":"https://www.youtube.com/watch?v=y39PrKY_4JM"},{"name":"Dumbbell bench press","prescription":"4 × 6","videoUrl":"https://www.youtube.com/watch?v=0G2_XV7slIg"},{"name":"Single-arm row","prescription":"3 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=pYcpY20QaE8"},{"name":"Half-kneeling press","prescription":"3 × 6 / side","videoUrl":"https://www.youtube.com/watch?v=M2rwvNhTOu0"},{"name":"Face pull","prescription":"2 × 12","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Side plank","prescription":"2 × 20s / side","notes":"Hips stacked. Stop if the low back takes over.","videoUrl":"https://www.youtube.com/watch?v=K2VljzCC16g"},{"name":"Suitcase carry","prescription":"2 × 20m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 3, 5, 8, 'Aerobic — slightly longer',
   'Stay conversational. If you cannot speak a sentence, ease off.',
   'https://www.youtube.com/watch?v=L_xrDAtykMI',
   '[{"name":"Easy walk-in","prescription":"5 min","notes":"Arrive unhurried.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Zone 2","prescription":"40–50 min","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"World''s greatest stretch","prescription":"2 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Cat-cow","prescription":"6 breaths","videoUrl":"https://www.youtube.com/watch?v=y39PrKY_4JM"},{"name":"Breathing reset","prescription":"5 min nasal, slow","videoUrl":"https://www.youtube.com/watch?v=tybOi4hjZFQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 4, 1, 9, 'Lower body — strength emphasis',
   'Top sets at a true 7/10 effort. No grinding.',
   'https://www.youtube.com/watch?v=MeIiIdhvXT4',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Nasal if you can. This is just to get warm.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"World''s greatest stretch","prescription":"2 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Glute bridge","prescription":"2 × 8","notes":"Pause at the top. Ribs down.","videoUrl":"https://www.youtube.com/watch?v=WCGV5XWewFY"},{"name":"Ankle rocks","prescription":"2 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Squat pattern","prescription":"4 × 5","videoUrl":"https://www.youtube.com/watch?v=MeIiIdhvXT4"},{"name":"Romanian deadlift","prescription":"3 × 5","notes":"Soft knees, long spine.","videoUrl":"https://www.youtube.com/watch?v=jEy_czb3RKA"},{"name":"Cossack squat","prescription":"2 × 6 / side","videoUrl":"https://www.youtube.com/watch?v=2C-uNgKwPLE"},{"name":"Dead bug","prescription":"2 × 6 / side","notes":"Low back stays quiet on the floor.","videoUrl":"https://www.youtube.com/watch?v=UBa7wBucN-4"},{"name":"Farmer carry","prescription":"2 × 30m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 4, 3, 10, 'Upper body — strength emphasis',
   'Pause the last rep of each set on the chest or at the hang.',
   'https://www.youtube.com/watch?v=0G2_XV7slIg',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Unhurried. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Band pull-apart","prescription":"2 × 12","notes":"Long spine. Stop if the shrug takes over.","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Cat-cow","prescription":"6 breaths","videoUrl":"https://www.youtube.com/watch?v=y39PrKY_4JM"},{"name":"Press","prescription":"4 × 5","videoUrl":"https://www.youtube.com/watch?v=0G2_XV7slIg"},{"name":"Row","prescription":"4 × 6","videoUrl":"https://www.youtube.com/watch?v=pYcpY20QaE8"},{"name":"Carry","prescription":"2 × 30m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"},{"name":"Face pull","prescription":"2 × 12","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Side plank","prescription":"2 × 20s / side","notes":"Hips stacked. Stop if the low back takes over.","videoUrl":"https://www.youtube.com/watch?v=K2VljzCC16g"},{"name":"Easy bike or walk","prescription":"6–8 min","notes":"Conversational. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 4, 5, 11, 'Easy aerobic — keep the week honest',
   'Do not turn this into intervals.',
   'https://www.youtube.com/watch?v=L_xrDAtykMI',
   '[{"name":"Easy walk-in","prescription":"5 min","notes":"Arrive unhurried.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Zone 2","prescription":"40 min","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Ankle rocks","prescription":"2 × 10 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Cat-cow","prescription":"6 breaths","videoUrl":"https://www.youtube.com/watch?v=y39PrKY_4JM"},{"name":"Breathing reset","prescription":"5 min nasal, slow","videoUrl":"https://www.youtube.com/watch?v=tybOi4hjZFQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 5, 1, 12, 'Lower body — power without chaos',
   'Crisp reps. Stop before the landing gets loud.',
   'https://www.youtube.com/watch?v=MeIiIdhvXT4',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Nasal if you can. This is just to get warm.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"World''s greatest stretch","prescription":"2 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Glute bridge","prescription":"2 × 8","notes":"Pause at the top. Ribs down.","videoUrl":"https://www.youtube.com/watch?v=WCGV5XWewFY"},{"name":"Ankle rocks","prescription":"2 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Squat pattern","prescription":"3 × 5","videoUrl":"https://www.youtube.com/watch?v=MeIiIdhvXT4"},{"name":"Box step-up","prescription":"3 × 5 / side","videoUrl":"https://www.youtube.com/watch?v=2C-uNgKwPLE"},{"name":"Broad jump (soft)","prescription":"3 × 3","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"},{"name":"Dead bug","prescription":"2 × 6 / side","notes":"Low back stays quiet on the floor.","videoUrl":"https://www.youtube.com/watch?v=UBa7wBucN-4"},{"name":"Suitcase carry","prescription":"2 × 20m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 5, 3, 13, 'Upper body — press, pull, carry',
   'A little more snap, same control.',
   'https://www.youtube.com/watch?v=0G2_XV7slIg',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Unhurried. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Band pull-apart","prescription":"2 × 12","notes":"Long spine. Stop if the shrug takes over.","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Cat-cow","prescription":"6 breaths","videoUrl":"https://www.youtube.com/watch?v=y39PrKY_4JM"},{"name":"Press","prescription":"3 × 5","videoUrl":"https://www.youtube.com/watch?v=0G2_XV7slIg"},{"name":"Row","prescription":"3 × 6","videoUrl":"https://www.youtube.com/watch?v=pYcpY20QaE8"},{"name":"Farmer carry","prescription":"3 × 30m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"},{"name":"Face pull","prescription":"2 × 12","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Side plank","prescription":"2 × 20s / side","notes":"Hips stacked. Stop if the low back takes over.","videoUrl":"https://www.youtube.com/watch?v=K2VljzCC16g"},{"name":"Easy bike or walk","prescription":"6–8 min","notes":"Conversational. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 5, 5, 14, 'Aerobic — steady',
   'Same easy pace. This week is about arriving recovered.',
   'https://www.youtube.com/watch?v=L_xrDAtykMI',
   '[{"name":"Easy walk-in","prescription":"5 min","notes":"Arrive unhurried.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Zone 2","prescription":"40–45 min","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Breathing reset","prescription":"5 min nasal, slow","videoUrl":"https://www.youtube.com/watch?v=tybOi4hjZFQ"},{"name":"Hip 90/90","prescription":"2 × 45s / side","videoUrl":"https://www.youtube.com/watch?v=MH919hRvrVE"},{"name":"Easy walk-out","prescription":"5 min","notes":"Unhurried. Write a word for how the week felt.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 6, 1, 15, 'Lower body — settle and note',
   'Repeat a week-4 load if it still feels quiet. Write down what moved well.',
   'https://www.youtube.com/watch?v=MeIiIdhvXT4',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Nasal if you can. This is just to get warm.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"World''s greatest stretch","prescription":"2 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Glute bridge","prescription":"2 × 8","notes":"Pause at the top. Ribs down.","videoUrl":"https://www.youtube.com/watch?v=WCGV5XWewFY"},{"name":"Ankle rocks","prescription":"2 × 8 / side","videoUrl":"https://www.youtube.com/watch?v=-rK5otzYmt4"},{"name":"Squat pattern","prescription":"3 × 5","videoUrl":"https://www.youtube.com/watch?v=MeIiIdhvXT4"},{"name":"Hinge","prescription":"3 × 5","notes":"Soft knees, long spine.","videoUrl":"https://www.youtube.com/watch?v=jEy_czb3RKA"},{"name":"Calf raise","prescription":"2 × 12","videoUrl":"https://www.youtube.com/watch?v=gwLzBJYoWlI"},{"name":"Dead bug","prescription":"2 × 6 / side","notes":"Low back stays quiet on the floor.","videoUrl":"https://www.youtube.com/watch?v=UBa7wBucN-4"},{"name":"Farmer carry","prescription":"2 × 30m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 6, 3, 16, 'Upper body — settle and note',
   'Same idea as Tuesday. This is a checkpoint, not a test day.',
   'https://www.youtube.com/watch?v=0G2_XV7slIg',
   '[{"name":"Easy bike or walk","prescription":"5 min","notes":"Unhurried. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Band pull-apart","prescription":"2 × 12","notes":"Long spine. Stop if the shrug takes over.","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Cat-cow","prescription":"6 breaths","videoUrl":"https://www.youtube.com/watch?v=y39PrKY_4JM"},{"name":"Press","prescription":"3 × 5","videoUrl":"https://www.youtube.com/watch?v=0G2_XV7slIg"},{"name":"Row","prescription":"3 × 6","videoUrl":"https://www.youtube.com/watch?v=pYcpY20QaE8"},{"name":"Carry","prescription":"2 × 30m","videoUrl":"https://www.youtube.com/watch?v=Tgi5SNDbBZQ"},{"name":"Face pull","prescription":"2 × 12","videoUrl":"https://www.youtube.com/watch?v=rep-qVOkqgk"},{"name":"Side plank","prescription":"2 × 20s / side","notes":"Hips stacked. Stop if the low back takes over.","videoUrl":"https://www.youtube.com/watch?v=K2VljzCC16g"},{"name":"Easy bike or walk","prescription":"6–8 min","notes":"Conversational. Shake the arms out.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"}]'::jsonb),
  ('11111111-1111-1111-1111-111111111111', '22222222-2222-2222-2222-222222222222', 6, 5, 17, 'Easy finish',
   'Walk, breathe, write a short note for your coach. The next block starts from here.',
   'https://www.youtube.com/watch?v=L_xrDAtykMI',
   '[{"name":"Easy walk-in","prescription":"5 min","notes":"Arrive unhurried.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Zone 2","prescription":"30–40 min","notes":"Easy finish. Write a short note for your coach.","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Full-body mobility","prescription":"8–10 min","videoUrl":"https://www.youtube.com/watch?v=L_xrDAtykMI"},{"name":"Couch stretch","prescription":"2 × 40s / side","videoUrl":"https://www.youtube.com/watch?v=ulgAOykAgV4"},{"name":"Breathing reset","prescription":"5 min nasal, slow","videoUrl":"https://www.youtube.com/watch?v=tybOi4hjZFQ"}]'::jsonb)
on conflict (program_id, week, day, sort_order) do update
  set title = excluded.title,
      notes = excluded.notes,
      video_url = excluded.video_url,
      segments = excluded.segments;

insert into public.program_assignments (id, tenant_id, program_id, member_email, status)
values (
  '33333333-3333-3333-3333-333333333333',
  '11111111-1111-1111-1111-111111111111',
  '22222222-2222-2222-2222-222222222222',
  'member@ajax.local',
  'active'
)
on conflict (id) do update
  set program_id = excluded.program_id,
      member_email = excluded.member_email,
      status = excluded.status;
